version: "3"

services:
  app:
    command: "poetry run uvicorn blt.asgi:application --host 0.0.0.0 --port 8000"
    build: .
    volumes:
      - .:/blt
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
  cache:
    command: "redis-server"
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local